#!/bin/sh

NOCOLOR='\e[0m'
REDCOLOR='\e[37;41m'

yesOrNo() {
    local message
    local default
    if [ "$2" = "y" ]; then message="$1 [Y/n]"; default='yes';
    elif [ "$2" = "n" ]; then message="$1 [y/N]"; default='no';
    else message="$1 [y/n]"; default=false;
    fi

    local yesNoAnswer=''
    while [ -n $yesNoAnswer ]; do
        read -p "$message " yesNoAnswer
        case $yesNoAnswer in
            [yY]|[yY][eE][sS])
                echo 'yes'
                exit
            ;;
            [nN]|[nN][oO])
                echo 'no'
                exit
            ;;
            '')
                if $default; then
                    echo "$default"
                    exit
                fi
            ;;
        esac
    done
}


if [ `git diff HEAD@{1} --stat -- package.json` != "" ]; then
    if [[ `yesOrNo "package.json has changed. Do you want to run 'npm install' ?` == 'yes']]; then
        npm install
    else
        echo -e "$REDCOLOR" "package.json has changed. You should run npm install$NOCOLOR"
    fi
fi
