name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache

      - name: Build
        run: yarn run build
        if: startsWith(matrix.node-version, '18.')

      - name: Prettier
        run: yarn run lint:prettier
        if: startsWith(matrix.node-version, '18.')

      - name: Typescript
        run: yarn run tsc
        if: startsWith(matrix.node-version, '18.')

      - name: Eslint
        run: yarn run lint:eslint
        if: startsWith(matrix.node-version, '18.')

      - name: Test
        run: yarn run test
        env:
          CI: true

      - name: Check nothing was forgotten before commit
        if: startsWith(matrix.node-version, '18.')
        run: yarn run repository-check-dirty

      - uses: GoogleCloudPlatform/release-please-action@v3
        if: ${{ startsWith(matrix.node-version, '18.') && github.ref == 'refs/heads/main' }}
        id: release
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: node
          package-name: release-please-action

      # publish:
      - run: npm publish
        if: ${{ startsWith(matrix.node-version, '18.') && github.ref == 'refs/heads/main' && steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
